import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";
import NavBarGlobal from "./components/NavBarGlobal";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Renders the root layout of the application.
 * @param {Object} props - The props object.
 * @param {React.ReactNode} props.children - The child components to be rendered.
 * @returns {JSX.Element} - The root layout component.
 */
export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <main className={inter.className}>
          <NavBarGlobal />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
